# Generated by Django 4.0 on 2021-12-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_employees_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
