# Generated by Django 4.0 on 2021-12-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_department_slug_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='staff.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='staff.post', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post', to='staff.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Должность'),
        ),
    ]
